version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server  # Points to the server folder
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build: 
      context: ./client # Points to the client folder
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  pgdata: